#!/bin/sh
set -eu

case "$1" in
  configure)
    if ! getent group spi >/dev/null 2>&1; then
      addgroup --system spi >/dev/null 2>&1 || true
    fi

    dkms add -m spibridge -v 1.1 || true
    dkms build -m spibridge -v 1.1 || true
    dkms install -m spibridge -v 1.1 || true

    systemctl daemon-reload || true
    systemctl enable spi-bridge.service >/dev/null 2>&1 || true
    systemctl restart spi-bridge.service >/dev/null 2>&1 || true

    udevadm control --reload-rules || true
    udevadm trigger || true
    ;;
esac

exit 0
